# Site settings
title: Idealogy Labs - Next Generation IT Infrastructure Services and Solutions | Startup Acceleration | Product Development | Extended Teams | CyberSecurity | Cloud Infrastructure Services | Mobility Services | IoT(Internet of Things) Services
email: connect@idealogylabs.com
description: > # Next Generation IT Infrastructure Services and Solutions | Startup Acceleration | 
  Product Development | Extended Teams | CyberSecurity | Cloud/Mobility Services | Cloud Infrastructure 
  Implementation and Automation | Agile Development |  Web Development | Ruby Experts | Ruby on Rails Experts | 
  Python Experts | Golang Experts | Elixir/Erlang Experts | MongoDB Experts | Mobile Experts | IoT(Internet of Things) 
  Experts | Vulnerability Testing | Brute Force Testing | Technology eNabled services and trainings
og: 
  description: > # 
    Agile Development |  Web Development | Ruby Experts | Ruby on Rails Experts | Python Experts | 
    Golang Experts | Elixir/Erlang Experts | MongoDB Experts | Mobile Experts | IoT(Internet of Things) Experts | 
    Vulnerability Testing | Brute Force Testing | Technology eNabled services and trainings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://idealogylabs.com" # the base hostname & protocol for your site
twitter_url: https://twitter.com/idealogylabs
github_url:  https://github.com/idealogylabs
facebook_url: https://www.facebook.com/idealogylabs
linkedin_url: https://www.linkedin.com/company/idealogy-labs-pvt-ltd
google_plus_url: https://plus.google.com/+Idealogylabstech
youtube_url: https://www.youtube.com/c/idealogylabstech
company: IdealogyLabs Technologies Pvt Ltd
brandname: IdealogyLabs
permalink: /blog/:categories/:year/:month/:day/:title.html

# Build settings
markdown: kramdown
